FROM php:7.3-apache

RUN apt-get update && apt-get install -y wget libpng-dev libjpeg-dev gnupg default-mysql-client nano less unzip && rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd \
	&& docker-php-ext-install gd mysqli

RUN a2enmod rewrite

COPY update.sh /var/www/html

COPY config/php.ini /usr/local/etc/php

COPY config/.htaccess /var/www/html

RUN curl -o /bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x /bin/wp \
  && wp --info --allow-root;

RUN curl -sS https://getcomposer.org/installer --output composer-setup.php \
  && php composer-setup.php --version=1.10.16 \
  && mv composer.phar /bin/composer

<% versions.forEach((version) => { %>
RUN curl https://wordpress.org/wordpress-<%= version %>.tar.gz > wordpress-<%= version %>.tar.gz && \
  mkdir -p /var/www/<%= version %> && \
  tar -xzf wordpress-<%= version %>.tar.gz -C /var/www/<%= version %> && \
  mv /var/www/<%= version %>/wordpress/* /var/www/<%= version %> && \
  rm -rf /var/www/<%= version %>/wordpress && \
  chown -R www-data:www-data /var/www/<%= version %><% if (isWpContent) { %> && \<% } else { %>;<% } %>
  <% if (isWpContent) { %>rm -rf /var/www/<%= version %>/wp-content;<% } %>
<% }); %>

<% if (vip) { %>
RUN curl https://github.com/Automattic/vip-go-mu-plugins-built/archive/master.zip -L -o /usr/src/vip-mu-plugins.zip && \
  unzip /usr/src/vip-mu-plugins.zip -d /var/www/html/wp-content && cd /var/www/html/wp-content && mv vip-go-mu-plugins-built-master mu-plugins
<% } %>

EXPOSE 80

CMD ["apache2-foreground"]
