FROM php:<%= phpVersion %>-apache

RUN apt-get update && apt-get install -y wget rsync libpng-dev libjpeg-dev gnupg default-mysql-client nano less unzip && rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd \
	&& docker-php-ext-install gd mysqli

RUN a2enmod rewrite

COPY update.sh <%= workingDir %>/html

ENV PHP_MEMORY_LIMIT=<%= phpMemoryLimit %>

COPY config/php.ini /usr/local/etc/php

COPY config/<%= htaccessFile %> <%= workingDir %>/html/.htaccess

RUN curl -o /bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x /bin/wp \
  && wp --info --allow-root;

RUN curl -sS https://getcomposer.org/installer --output composer-setup.php \
  && php composer-setup.php --version=1.10.16 \
  && mv composer.phar /bin/composer

<% versions.forEach((version) => {
     if ( version.match(/(\d+.?)+/) ) {
%>
RUN curl https://wordpress.org/wordpress-<%= version %>.tar.gz > wordpress-<%= version %>.tar.gz && \
  mkdir -p <%= workingDir %>/<%= version %> && \
  tar -xzf wordpress-<%= version %>.tar.gz -C <%= workingDir %>/<%= version %> && \
  mv <%= workingDir %>/<%= version %>/wordpress/* <%= workingDir %>/<%= version %> && \
  rm -rf <%= workingDir %>/<%= version %>/wordpress && \
  chown -R www-data:www-data <%= workingDir %>/<%= version %><% if (isWpContent) { %> && \<% } else { %>;<% } %>
  <% if (isWpContent) { %>rm -rf <%= workingDir %>/<%= version %>/wp-content;<% } %>
<% } else { %>
ADD <%= version %> /var/www/wordpress
RUN chown -R www-data:www-data /var/www/wordpress
<% } }); %>

<% if (vip) { %>
RUN curl https://github.com/Automattic/vip-go-mu-plugins-built/archive/master.zip -L -o /usr/src/vip-mu-plugins.zip && \
  unzip /usr/src/vip-mu-plugins.zip -d <%= workingDir %>/html/wp-content && cd <%= workingDir %>/html/wp-content && mv vip-go-mu-plugins-built-master mu-plugins
<% } %>

EXPOSE 80

CMD ["apache2-foreground"]
